'use client';
import { Inter } from 'next/font/google';
import './globals.css';

import {
  NavigationMenu,
  NavigationMenuContent,
  NavigationMenuIndicator,
  NavigationMenuItem,
  NavigationMenuLink,
  NavigationMenuList,
  NavigationMenuTrigger,
  NavigationMenuViewport,
} from '@/components/ui/navigation-menu';

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className="bg-slate-200">
          <nav className="p-8">
            <ui
              className="flex justify-center"
              style={{ listStyleType: 'none' }}
            >
              <li className="mx-3">item 1</li>
              <li className="mx-3">item 1</li>
              <li className="mx-3">item 1</li>
            </ui>
          </nav>
        </div>
        {children}
      </body>
    </html>
  );
}
