export const ecomData = [
  {
    productId: 1,
    productName: 'T-Shirt concept 2',
    price: 9.99,
    stock: 50,
    category: 'UpperBody',
    categoryId: 1,
  },
  {
    productId: 2,
    productName: 'Alpha Flys',
    price: 79.99,
    stock: 100,
    category: 'Footwear',
    categoryId: 2,
  },
  {
    productId: 3,
    productName: 'Pull up bar',
    price: 49.99,
    stock: 30,
    category: 'Equipment',
    categoryId: 3,
  },
  {
    productId: 4,
    productName: 'Backpack',
    price: 39.99,
    stock: 80,
    category: 'Accessories',
    categoryId: 4,
  },
  {
    productId: 5,
    productName: 'Vitamin D',
    price: 29.99,
    stock: 20,
    category: 'Supplements',
    categoryId: 5,
  },
  {
    productId: 6,
    productName: 'Grey joggers',
    price: 39.99,
    stock: 50,
    category: 'LowerBody',
    categoryId: 6,
  },
  {
    productId: 7,
    productName: 'Blue joggers',
    price: 39.99,
    stock: 50,
    category: 'LowerBody',
    categoryId: 6,
  },
  {
    productId: 8,
    productName: 'Grey joggers',
    price: 39.99,
    stock: 50,
    category: 'LowerBody',
    categoryId: 6,
  },
  {
    productId: 9,
    productName: 'Muscle fit T',
    price: 19.99,
    stock: 50,
    category: 'UpperBody',
    categoryId: 1,
  },
  {
    productId: 10,
    productName: 'Pump cover hoodie',
    price: 39.99,
    stock: 50,
    category: 'UpperBody',
    categoryId: 1,
  },
  {
    productId: 11,
    productName: 'Short shorts',
    price: 29.99,
    stock: 50,
    category: 'LowerBody',
    categoryId: 6,
  },
  {
    productId: 12,
    productName: 'Weightlifting Gloves',
    price: 24.99,
    stock: 40,
    category: 'Accessories',
    categoryId: 4,
  },
  {
    productId: 13,
    productName: 'Protein Shaker Bottle',
    price: 12.99,
    stock: 60,
    category: 'Accessories',
    categoryId: 4,
  },
  {
    productId: 14,
    productName: 'Resistance Bands Set',
    price: 34.99,
    stock: 25,
    category: 'Equipment',
    categoryId: 3,
  },
  {
    productId: 15,
    productName: 'Running Shoes',
    price: 89.99,
    stock: 70,
    category: 'Footwear',
    categoryId: 2,
  },
  {
    productId: 16,
    productName: 'Yoga Mat',
    price: 19.99,
    stock: 35,
    category: 'Equipment',
    categoryId: 3,
  },
  {
    productId: 17,
    productName: 'Compression Sleeves',
    price: 29.99,
    stock: 30,
    category: 'Accessories',
    categoryId: 4,
  },
  {
    productId: 18,
    productName: 'Hydration Backpack',
    price: 49.99,
    stock: 45,
    category: 'Accessories',
    categoryId: 4,
  },
  {
    productId: 19,
    productName: 'BCAA (Branched-Chain Amino Acids)',
    price: 27.99,
    stock: 20,
    category: 'Supplements',
    categoryId: 5,
  },
  {
    productId: 20,
    productName: 'CrossFit Kettlebell',
    price: 44.99,
    stock: 15,
    category: 'Equipment',
    categoryId: 3,
  },
  {
    productId: 21,
    productName: 'Performance Tank Top',
    price: 22.99,
    stock: 55,
    category: 'UpperBody',
    categoryId: 1,
  },
];
